### ISSUE TITLE
Restore purchases button not responding

### ISSUE THREAD

**Issue by JVariance** [tschiekdev/Noteful-Issues#7]
I got a new phone (Galaxy S20 FE, Android 12) and try to restore the purchases, but it doesn't work.
I'm logged into the same Google account I bought the features with.

**Comment by tschiekdev** [comment]
Possibly the purchases were refunded automatically? There was a bug in the app a long time ago, so purchases were automatically refunded.
Otherwise I don't know what could be the reason. Basically it works.
